src/grand-search/gui/exhibition/matchresult/listview/grandsearchlistdelegate.cpp, tests/grand-search/gui/exhibition/matchresult/listview/ut_grandsearchlistdelegate.cpp, tests/grand-search/gui/ut_mainwindow.cpp
fix the bug about hovert color
Log: 深色模式下鼠标悬浮在类目上背景色为一定透明度的白色
Bug: https://pms.uniontech.com/bug-view-134981.html
Influence: 深色模式下鼠标悬浮在类目上背景色为一定透明度的白色
Change-Id: I079b8e93d88a008670e21bc849838cb0e2bf8f69
=> fix: fix the bug about hovert color

src/grand-search-daemon/configuration/configer.cpp, src/grand-search-daemon/configuration/configer_p.h, src/grand-search/CMakeLists.txt, src/grand-search/gui/searchconfig/blacklistview/blacklistdelegate.cpp, src/grand-search/gui/searchconfig/blacklistview/blacklistdelegate.h, src/grand-search/gui/searchconfig/blacklistview/blacklistmodel.cpp, src/grand-search/gui/searchconfig/blacklistview/blacklistmodel.h, src/grand-search/gui/searchconfig/blacklistview/blacklistview.cpp, src/grand-search/gui/searchconfig/blacklistview/blacklistview.h, src/grand-search/gui/searchconfig/blacklistview/deletedialog.cpp, src/grand-search/gui/searchconfig/blacklistview/deletedialog.h, src/grand-search/gui/searchconfig/blacklistwidget.cpp, src/grand-search/gui/searchconfig/blacklistwidget.h, src/grand-search/gui/searchconfig/configwidget.cpp, src/grand-search/gui/searchconfig/configwidget.h, src/grand-search/gui/searchconfig/indexwidget.cpp, src/grand-search/gui/searchconfig/indexwidget.h, src/grand-search/gui/searchconfig/searchenginewidget.cpp
add path blacklist configuration in the setting interface
Log: users can add paths to the exclusion list to prevent searching in them
Task: https://pms.uniontech.com/task-view-110869.html
Change-Id: I5014d879557cc063b4822adac5447c2df832db34
=> feat: add path blacklist configuration

src/grand-search-daemon/searcher/file/filesearchutils.cpp, src/grand-search/gui/searchconfig/blacklistview/blacklistview.cpp, src/grand-search/gui/searchconfig/blacklistview/blacklistview.h, src/grand-search/gui/searchconfig/blacklistview/deletedialog.cpp, src/grand-search/gui/searchconfig/blacklistwidget.cpp
fix the bugs on blacklist including 144083, 144109, 144171
Log: 确认按钮文本为红色，拖拽目录清除原选中项，屏蔽路径本身目录文件
Bug: https://pms.uniontech.com/bug-view-144083.html https://pms.uniontech.com/bug-view-144109.html https://pms.uniontech.com/bug-view-144171.html
Influence: 按钮颜色调整，拖拽添加清除原选中项，搜索结果屏蔽路径本身
=> fix: fix the bugs

src/grand-search/gui/searchconfig/blacklistview/blacklistview.cpp, src/grand-search/gui/searchconfig/blacklistview/deletedialog.cpp
fix the bug 144853
Log: 确认删除对话框文本字体大小与UI一致，路径黑名单设置界面边框显示
Bug: https://pms.uniontech.com/bug-view-144853.html
Influence: 确认删除对话框文本大小与UI一致，路径黑名单设置界面边框正常显示
=> fix: fix the bug 144853

debian/control, src/preview-plugin/audio-preview/CMakeLists.txt, src/preview-plugin/audio-preview/audiopreviewinterface.cpp, src/preview-plugin/audio-preview/audiopreviewinterface.h, src/preview-plugin/audio-preview/audiopreviewplugin.cpp, src/preview-plugin/audio-preview/audiopreviewplugin.h, src/preview-plugin/audio-preview/libaudioviewer.cpp, src/preview-plugin/audio-preview/libaudioviewer.h, src/preview-plugin/video-preview/CMakeLists.txt, src/preview-plugin/video-preview/libvideoviewer.cpp, src/preview-plugin/video-preview/libvideoviewer.h, src/preview-plugin/video-preview/videopreviewinterface.cpp, src/preview-plugin/video-preview/videopreviewplugin.cpp, src/preview-plugin/video-preview/videopreviewplugin.h, tests/preview-plugin/audio-preview/ut_audiopreviewplugin.cpp, tests/preview-plugin/audio-preview/ut_libaudioviewer.cpp, tests/preview-plugin/video-preview/ut_libvideoviewer.cpp, tests/preview-plugin/video-preview/ut_videopreviewplugin.cpp
1, loading imageeditor dynamically to   get video or audion information.
2. remove remove duplicate dependencies in debian/control.
Log: 使用imageeditor预览音视频。
Task: https://pms.uniontech.com/task-view-165263.html
Influence: 音频、视频预览
=> feat: using imageeditor to get video information.

src/grand-search-daemon/searcher/app/desktopappsearcher.cpp
避免硬编码，并解决因原本实现导致的顺序覆盖问题。
原本的实现中，硬编码了 APPLICATION_DIR_PATH （`/usr/share/applications`） 与 APPLICATIONLOCAL_DIR_PATH（`/usr/local/share/applications`），然后将 `QStandardPaths::ApplicationsLocation` 作为补充路径添加到了查找位置中，但这样的实现存在问题：
1. 根据文档，在 Linux 环境中，[`QStandardPaths::ApplicationsLocation` 本身即包含这两个被硬编码进去的路径](https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum)，故原本的逻辑看上去本身就是多余的。
2. 在常见的情况中，可能存在路径 `~/.local/share/applications`。当此路径存在时，此路径下所放置的 desktop 文件应当**优先于**位于 `/usr/share` 与 `/usr/local/share` 下放置的 desktop 文件。目前的实现逻辑会导致用户目录下的文件无法覆盖系统目录下的 desktop 文件，使行为不符合相关的 XDG 规范。
3. 应当尽可能避免硬编码路径，相关 Issue：https://github.com/linuxdeepin/developer-center/issues/3374
修复验证方式：
1. 从系统 application 目录下复制一个 desktop 文件，放置于用户目录的 application 对应目录下，修改其 Exec 字段使其与原有行为不同，最终保存文件并保持相同的文件名
2. 构建代码，并启动修改或的版本所得到的 …
=> fix: should use QStandardPath for Application path

tests/grand-search-daemon/searcher/app/ut_desktopappsearcher.cpp
the appliation path that reseted by XDG_DATA_DIRS will not contain defalut path.
Log:
Influence: 无
=> chore: fix ut failed

CMakeLists.txt
Log: Use as-needed to enhance compatibility with linker
linuxdeepin/developer-center#3345
=> fix: use as-needed instead of as-need

src/grand-search/gui/searchconfig/configwidget.cpp
QScrollArea reduce width of viewport if its width is wider than scroll area with ScrollBarAsNeeded. Set scroll bar policy to ScrollBarAlwaysOn to work around.
Log:
Bug: https://pms.uniontech.com/bug-view-184053.html
=> fix: config widget is incomplete

3rdparty/fsearch/fsearch_thread_pool.c
It is recommended to use 'g_list_free' to free GList objects
Log: fix issue
=> fix: The daemon crashed during exit

src/libgrand-search-daemon/utils/chineseletterhelper.cpp, src/libgrand-search-daemon/utils/dict.qrc
The grand search library contains the pinyin.dict file which is also contained in dfmbase . It results that the grand search read the pinyin.dict that is in dfmbase instead of itself  one after attaching grand search to dfm server.
Log: 
Bug: https://pms.uniontech.com/bug-view-200093.html
Influence: 全局搜索
=> fix: Pinyin.dict is covered by same one in dfmbase

src/grand-search-dock-plugin/gui/grandsearchwidget.cpp
The font size of the system is set to the largest, and some of the text in the shortcut panel is incomplete.
Log: The quick panel plugin not show correct.
Bug: https://pms.uniontech.com/bug-view-260963.html
=> fix: The quick panel plugin not show correct

3rdparty/fsearch/fsearch_thread_pool.c
After adding this as patch, it built successfully. close https://github.com/linuxdeepin/developer-center/issues/10622
Ref: https://copr.fedorainfracloud.org/coprs/topazus/dde/build/8003640/
https://man7.org/linux/man-pages/man3/usleep.3.html
=> Fix build on aarch64

3rdparty/fsearch/database.c
Recursive search for files in the directory, recursive 200 layers causing stack overflow
Log: dde-grand-search crash
Bug: https://pms.uniontech.com/bug-view-270417.html
=> fix: dde-grand-search crash

src/grand-search/gui/exhibition/preview/generalwidget/aitoolbar.cpp
1. Do not pull up the UOS AI process during preview.
2. When clicking the preview button, execute the task usingdbus.
Log:
=> fix: Modify the request for uos AI interface

src/grand-search/gui/exhibition/preview/generalwidget/aitoolbar.cpp, src/grand-search/gui/exhibition/preview/generalwidget/aitoolbar.h
Description: 点击总结后，页面未消失，再次点击总结，uos ai页面关闭再也无法唤起
Log:
Bug: https://pms.uniontech.com/bug-view-281009.html
=> fix: 点击总结后，页面未消失，再次点击总结，uos ai页面关闭再也无法唤起

src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.cpp
Description: 自动更新索引 先显示开启后又自动跳到关闭
Log:
Bug: https://pms.uniontech.com/bug-view-283013.html
=> fix: 自动更新索引 先显示开启后又自动跳到关闭

src/grand-search/gui/exhibition/preview/previewwidget.cpp, src/preview-plugin/text-preview/textview.cpp
Description: 当文件后缀为大写时，未呈现uos ai相关入口
Log:
Bug: BUG-292765
=> fix: 当文件后缀为大写时，未呈现uos ai相关入口

src/grand-search/CMakeLists.txt, src/grand-search/gui/searchconfig/indexwidget.cpp
Description: 【ARM64】【LOONG64】if not AMD64 platform, do not show ai search config
Log:
Bug: BUG-295519
=> fix: 【ARM64】【LOONG64】if not AMD64 platform, do not show ai search config

src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.cpp
* Remove Qt version check for QRegularExpression options
* Use QRegularExpression::CaseInsensitiveOption consistently
* Remove Qt5 specific Qt::CaseInsensitive option
Log: adapt Qt6 QRegularExpression option
=> chore: adapt Qt6 QRegularExpression option

src/grand-search-dock-plugin/CMakeLists.txt
* Replace commented version check with proper CMake generator expression
* Use standard CMake LESS operator instead of < operator
* Clean up QGSettings conditional compilation for Qt5/6
* Remove trailing empty lines
Log: improve Qt version check in CMake
=> fix: improve Qt version check in CMake

src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.cpp, src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.h, src/dde-grand-search-daemon/searcher/semantic/semanticworker.cpp
=> feat: DSL search improvement

3rdparty/fsearch/array.c, debian/changelog
Fix build issue on arm64 and loong64, update new tag 5.5.13
Log: New tag v5.5.13
=> fix: [tag]New tag v5.5.13

debian/control, src/dde-grand-search-daemon/CMakeLists.txt, src/tools/luceneengine/CMakeLists.txt, src/tools/semanticparser/CMakeLists.txt
=> fix: 修复后端为qt5启动

src/grand-search/gui/mainwindow.cpp
- Add visibleChanged signal emission in closeEvent
- Ensure visibility state is properly updated before window closes
Log: emit visible changed signal when window closing
=> fix: emit visible changed signal when window closing

src/grand-search/utils/utils.cpp
Wait for dbus call to complete when opening extended search matched items
Log: handle dbus call asynchronously for plugin item opening
Bug: https://pms.uniontech.com/bug-view-305007.html
=> fix: improve plugin item opening with async dbus call

CMakeLists.txt, debian/control, src/dde-grand-search-daemon/CMakeLists.txt, src/tools/luceneengine/CMakeLists.txt, src/tools/semanticparser/CMakeLists.txt
- Remove Qt5 dependencies from debian/control
- Update CMake files to support Qt6
- Add version requirement for libdeepin-service-framework-dev (>1.0.9)
- Remove hardcoded Qt5/Dtk namespace settings
Log: migrate to Qt6 by default
=> chore: migrate to Qt6 by default

debian/control
Add libdfm-search as a runtime dependency for the dde-grand-search package in debian/control. This ensures the search functionality has access to the required file manager search library.
Log: add libdfm-search dependency to dde-grand-search package
=> feat: add libdfm-search dependency to dde-grand-search package
