linuxdeepin/dde-grand-search

.gitignore
src/grand-search/utils/utils.cpp

详细情况：(linuxdeepin/developer-center#3118)
Log: 修正manjaro下编译失败的问题

fix: error: template with C linkage

---

src/grand-search/gui/searchconfig/configwidget.cpp

fix the bug about asymmetric display of setting interface
Log: 修复设置界面显示不对称
Bug: https://pms.uniontech.com/bug-view-134971.html
Influence: 设置界面显示对称

fix: asymmetric display of setting interface

---

src/grand-search/gui/searchconfig/blacklistview/deletedialog.cpp
src/grand-search/gui/searchconfig/blacklistview/deletedialog.h
src/grand-search/gui/searchconfig/blacklistwidget.cpp
src/grand-search/gui/searchconfig/blacklistwidget.h
src/grand-search/gui/searchconfig/customwidget.cpp

using return value of dialog::exec to confirm.
Log: 优化删除流程
Task: https://pms.uniontech.com/task-view-110869.html
Influence: 搜索设置

feat: optimize usage of deletedialog.

---

src/grand-search/gui/searchconfig/blacklistview/deletedialog.cpp
src/grand-search/gui/searchconfig/blacklistwidget.cpp
src/grand-search/gui/searchconfig/indexwidget.cpp
translations/dde-grand-search.ts
translations/dde-grand-search_az.ts
translations/dde-grand-search_ca.ts
translations/dde-grand-search_cs.ts
translations/dde-grand-search_de.ts
translations/dde-grand-search_fi.ts
translations/dde-grand-search_fr.ts
translations/dde-grand-search_it.ts
translations/dde-grand-search_nl.ts
translations/dde-grand-search_pl.ts
translations/dde-grand-search_pt_BR.ts
translations/dde-grand-search_sq.ts
translations/dde-grand-search_tr.ts
translations/dde-grand-search_uk.ts
translations/dde-grand-search_zh_CN.ts
translations/dde-grand-search_zh_HK.ts
translations/dde-grand-search_zh_TW.ts

Update translation.
Log: 更新翻译
Task: https://pms.uniontech.com/task-view-116711.html
Influence:

chore: update translation

---

tests/grand-search-daemon/configuration/ut_configer.cpp
tests/grand-search/gui/searchconfig/blacklistview/ut_blacklistdelegate.cpp
tests/grand-search/gui/searchconfig/blacklistview/ut_blacklistmodel.cpp
tests/grand-search/gui/searchconfig/blacklistview/ut_blacklistview.cpp
tests/grand-search/gui/searchconfig/blacklistview/ut_deletedialog.cpp
tests/grand-search/gui/searchconfig/ut_blacklistwidget.cpp
tests/grand-search/gui/searchconfig/ut_indexwidget.cpp

add ut about blacklist
Log:
Influence: 无

chore: add ut about blacklist

---

tests/grand-search/gui/searchconfig/ut_indexwidget.cpp

resolve memory leaks of ut
Log: resolve memory leaks
Influence: 无

chore: resolve memory leaks

---

CMakeLists.txt
src/buryingpoint/basicpoint.cpp
src/buryingpoint/basicpoint.h
src/buryingpoint/buryingpointfactory.cpp
src/buryingpoint/buryingpointfactory.h
src/buryingpoint/eventlogutil/eventlogutil.cpp
src/buryingpoint/eventlogutil/eventlogutil.h
src/buryingpoint/launchapppoint.cpp
src/buryingpoint/launchapppoint.h
src/grand-search/CMakeLists.txt
src/grand-search/main.cpp

add start data burying point function
Log: if appliction is started, relevant data will be collected.
Task: https://pms.uniontech.com/task-view-173243.html

feat: add data burying point function

---

src/grand-search/main.cpp

product demand change
Log : if application is started, relevant data will be collected.
Task: https://pms.uniontech.com/task-view-173243.html
Influence: Relevant data will be reported while user launched the application.

feat: product demand change

---

src/grand-search-daemon/data/dde-grand-search-daemon.desktop

Log: correct a typo in dde-grand-search-daemon.desktop

chore: correct a typo in dde-grand-search-daemon.desktop

---

CMakeLists.txt
src/grand-search-daemon/CMakeLists.txt
src/grand-search-dock-plugin/CMakeLists.txt

Log: use GNUInstallDirs in CmakeLists
https://github.com/linuxdeepin/developer-center/issues/3167

chore: use GNUInstallDirs in CmakeLists

---

translations/dde-grand-search.ts
translations/dde-grand-search_az.ts
translations/dde-grand-search_bo.ts
translations/dde-grand-search_ca.ts
translations/dde-grand-search_cs.ts
translations/dde-grand-search_de.ts
translations/dde-grand-search_en_US.ts
translations/dde-grand-search_es.ts
translations/dde-grand-search_fi.ts
translations/dde-grand-search_fr.ts
translations/dde-grand-search_hu.ts
translations/dde-grand-search_it.ts
translations/dde-grand-search_nl.ts
translations/dde-grand-search_pl.ts
translations/dde-grand-search_pt.ts
translations/dde-grand-search_pt_BR.ts
translations/dde-grand-search_ru.ts
translations/dde-grand-search_sl.ts
translations/dde-grand-search_sq.ts
translations/dde-grand-search_sr.ts
translations/dde-grand-search_tr.ts
translations/dde-grand-search_ug.ts
translations/dde-grand-search_uk.ts
translations/dde-grand-search_zh_CN.ts
translations/dde-grand-search_zh_HK.ts
translations/dde-grand-search_zh_TW.ts

update translations
Log: 更新翻译
Influence: 文案

chore: update translations

---

src/buryingpoint/basicpoint.h
src/buryingpoint/buryingpointfactory.cpp
src/buryingpoint/clickitempoint.cpp
src/buryingpoint/clickitempoint.h
src/grand-search/gui/exhibition/matchresult/listview/grandsearchlistview.cpp
src/grand-search/utils/utils.cpp
src/grand-search/utils/utils.h

add click item burying point
Log: if user open search result, relevant data will be collected.
Task: https://pms.uniontech.com/task-view-173243.html
Influence: 增加打开搜索结果埋点

feat: add click item burying point

---

src/buryingpoint/eventlogutil/committhread.cpp
src/buryingpoint/eventlogutil/committhread.h
src/buryingpoint/eventlogutil/eventlogutil.cpp
src/buryingpoint/eventlogutil/eventlogutil.h
tests/grand-search/CMakeLists.txt

code optimization
Log: code optimization

chore: Optimize EventLog module

---

.github/workflows/backup-to-gitlab.yml
.github/workflows/call-auto-tag.yml
.github/workflows/call-build-deb.yml
.github/workflows/call-chatOps.yml
.github/workflows/call-clacheck.yml
.github/workflows/call-commitlint.yml
.github/workflows/call-license-check.yml
.github/workflows/call-tag-build.yml
.github/workflows/cppcheck.yml

add workflows for github.
Log:

chore(CI): add workflows

---

debian/changelog

chore: update version to 5.4.3

---

src/grand-search/business/matchresult/matchcontroller.cpp
src/grand-search/gui/datadefine.h
src/grand-search/gui/exhibition/matchresult/groupwidget.cpp
src/grand-search/utils/utils.cpp
src/grand-search/utils/utils.h
src/libgrand-search-daemon/searcher/semantic/database/anythingquery.cpp
src/libgrand-search-daemon/searcher/semantic/database/anythingquery_p.h
src/libgrand-search-daemon/searcher/semantic/database/featurequery.cpp
src/libgrand-search-daemon/searcher/semantic/database/featurequery_p.h
src/libgrand-search-daemon/searcher/semantic/database/fulltextquery.cpp
src/libgrand-search-daemon/searcher/semantic/database/fulltextquery_p.h
src/libgrand-search-daemon/searcher/semantic/fileresultshandler.cpp
src/libgrand-search-daemon/searcher/semantic/fileresultshandler.h
src/libgrand-search-daemon/searcher/semantic/semanticworker.cpp
src/libgrand-search-daemon/searcher/semantic/semanticworker_p.h
src/tools/luceneengine/featurelibengine.cpp
src/tools/luceneengine/featurelibengine.h
src/tools/luceneengine/featurelibengine_p.h
src/tools/luceneengine/fulltextengine.cpp
src/tools/luceneengine/fulltextengine.h
src/tools/luceneengine/fulltextengine_p.h
src/tools/luceneengine/keyformatter.cpp
src/tools/luceneengine/keyformatter.h
translations/dde-grand-search.ts
translations/dde-grand-search_zh_CN.ts

1. calculate the weights of the matches
2. sort all itemby weight.

feat:calculate the weights of the matches

---

debian/control

add deepin-ai-daemon to recommends
Log: update dependences

feat: update dependences

---

src/grand-search/gui/searchconfig/planwidget.cpp
translations/dde-grand-search.ts
translations/dde-grand-search_az.ts
translations/dde-grand-search_bo.ts
translations/dde-grand-search_ca.ts
translations/dde-grand-search_cs.ts
translations/dde-grand-search_de.ts
translations/dde-grand-search_en_US.ts
translations/dde-grand-search_es.ts
translations/dde-grand-search_fi.ts
translations/dde-grand-search_fr.ts
translations/dde-grand-search_hu.ts
translations/dde-grand-search_it.ts
translations/dde-grand-search_nl.ts
translations/dde-grand-search_pl.ts
translations/dde-grand-search_pt.ts
translations/dde-grand-search_pt_BR.ts
translations/dde-grand-search_ru.ts
translations/dde-grand-search_sl.ts
translations/dde-grand-search_sq.ts
translations/dde-grand-search_sr.ts
translations/dde-grand-search_tr.ts
translations/dde-grand-search_ug.ts
translations/dde-grand-search_uk.ts
translations/dde-grand-search_zh_CN.ts
translations/dde-grand-search_zh_HK.ts
translations/dde-grand-search_zh_TW.ts

update search experience program
Log: 更新搜索体验计划文案
Task: https://pms.uniontech.com/task-view-290821.html

feat: update search experience program

---

src/global/searchconfigdefine.h
src/grand-search/gui/searchconfig/searchenginewidget.cpp
src/grand-search/gui/searchconfig/searchenginewidget.h
src/libgrand-search-daemon/configuration/configer.cpp
src/libgrand-search-daemon/searcher/web/statictextworker.cpp
translations/dde-grand-search_zh_CN.ts

feat: custom search engine

---

src/grand-search-dock-plugin/ddegrandsearchdockplugin.cpp

hide quick panel at invoking action .
Log:
Task: https://pms.uniontech.com/task-view-305337.html

feat: hide quick panel at invoking action

---

src/grand-search/utils/utils.cpp

Signed-off-by: black-desk <me@black-desk.cn>

fix: enable fallback for Utils::launchApp

---

.tx/deepin.conf
debian/changelog

chore: update version to 5.4.5

---

src/grand-search/utils/utils.cpp

dbus reply conversion error.
Log: 
Bug: https://pms.uniontech.com/bug-view-241939.html

fix: dbus reply conversion error

---

src/grand-search/gui/mainwindow.cpp
src/grand-search/gui/mainwindow.h

[dtk] adapter blurEffectWidget
Log: [dtk] adapter blurEffectWidget
Task: https://pms.uniontech.com/task-view-331537.html

chore: [dtk] adapter blurEffectWidget

---

debian/changelog

update version to 5.4.6
Log: update version to 5.4.6

chore: update version to 5.4.6

---

src/grand-search/gui/mainwindow.cpp

Change effect for openning window.
Log:
Task: https://pms.uniontech.com/bug-view-244347.html

fix: Change effect for openning window

---

src/grand-search/gui/mainwindow.cpp

Log: add dtkgui version control for openning window effect.
Task: https://pms.uniontech.com/bug-view-244347.html

fix: add dtkgui version control for openning window effect

---

.tx/deepin.conf
debian/changelog

update version to 5.4.7
Log: update version to 5.4.7

chore: update version to 5.4.7

---

src/grand-search/utils/utils.cpp

cannot find dock icon if application is launched by old application manager interface, use new AM interface.
Log: fix issue about app launch.
Bug: https://pms.uniontech.com/bug-view-251461.html

fix: [251461/dock] dock icon issue.

---

debian/changelog

as title.
Log: version update.

chore: [chglog] update version 5.4.8

---

debian/changelog

update the baseline version to 5.4.9
Log: update the baseline version to 5.4.9
Bug: no

feat: update to 5.4.9

---

src/grand-search/gui/exhibition/matchresult/groupwidget.cpp
src/grand-search/gui/exhibition/matchresult/matchwidget.cpp
src/libgrand-search-daemon/searcher/semantic/database/vectorquery.cpp
src/libgrand-search-daemon/searcher/semantic/database/vectorquery_p.h

Calculating the weight of search results through vector distance
Log: 
bug: https://pms.uniontech.com/bug-view-255623.html
bug: https://pms.uniontech.com/bug-view-255709.html

fix: Optimize sorting

---

translations/dde-grand-search.ts
translations/dde-grand-search_zh_CN.ts

feat: update translations

---

src/grand-search/utils/utils.cpp
src/grand-search/utils/utils.h
src/libgrand-search-daemon/searcher/semantic/database/anythingquery.cpp
src/libgrand-search-daemon/searcher/semantic/database/anythingquery_p.h
src/libgrand-search-daemon/searcher/semantic/database/featurequery.cpp
src/libgrand-search-daemon/searcher/semantic/database/featurequery_p.h
src/libgrand-search-daemon/searcher/semantic/database/fulltextquery.cpp
src/libgrand-search-daemon/searcher/semantic/database/fulltextquery_p.h
src/libgrand-search-daemon/searcher/semantic/database/vectorquery.cpp
src/libgrand-search-daemon/searcher/semantic/database/vectorquery_p.h
src/libgrand-search-daemon/searcher/semantic/fileresultshandler.h
src/libgrand-search-daemon/searcher/semantic/semanticworker.cpp
src/libgrand-search-daemon/searcher/semantic/semanticworker_p.h

fix: Using doble to store weights

---

CMakeLists.txt

chore:fouce to COMPILE ON v23

---

debian/changelog

update the baseline version to 5.5.0

chore: update version to 5.5.0

---

src/grand-search/gui/mainwindow.cpp

delay emit mainwindow‘s visible changed signal
Log: as title
Influence: can get VisibleChanged is true signal

fix: dbus cannot monitor the signal that VisibleChanged is true

---

src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.cpp
src/libgrand-search-daemon/configuration/configer.cpp
src/libgrand-search-daemon/searcher/semantic/semanticsearcher.cpp

Description: 开通自然语言索引，增加开启和停用的接口
Log: 开通自然语言索引，增加开启和停用的接口

feat: 开通自然语言索引，增加开启和停用的接口

---

debian/changelog

chore: update version to 5.5.1

---

src/libgrand-search-daemon/searcher/semantic/database/anythingquery.cpp
src/libgrand-search-daemon/searcher/semantic/database/anythingquery_p.h
src/libgrand-search-daemon/searcher/semantic/semantichelper.cpp

Description: 找图片类、音乐类功能的完善（无实体时）
Log: 找图片类、音乐类功能的完善（无实体时）

fix: 找图片类、音乐类功能的完善（无实体时）

---

debian/changelog

Description: update version to 5.5.2
Log: update version to 5.5.2

chore: update version to 5.5.2

---

debian/dde-grand-search.preinst

SIGTERM to dde-grand-search-daemon use `preinstall` script
Log: as title
Bug: https://pms.uniontech.com/bug-view-268325.html

fix: Upgrading the existence of coredump messages

---

src/dde-grand-search-daemon/configuration/configer.cpp
src/dde-grand-search-daemon/searcher/file/filenameworker.cpp
src/dde-grand-search-daemon/searcher/file/filenameworker_p.h
src/global/commontools.h
tests/grand-search/CMakeLists.txt
tests/grand-search/gui/exhibition/preview/ut_previewpluginmanager.cpp
tests/libgrand-search-daemon/CMakeLists.txt
tests/libgrand-search-daemon/configuration/ut_configer.cpp
tests/libgrand-search-daemon/searcher/file/ut_filenameworker.cpp
tests/libgrand-search-daemon/ut_commontools.cpp

Adapter disk path
Log: Adapter disk path
Task: https://pms.uniontech.com/task-view-204311.html

feat: Adapter disk path

---

debian/changelog

update version to 5.5.4
Log: update version to 5.5.4

chore: update version to 5.5.4

---

src/dde-grand-search-daemon/searcher/semantic/semanticsearcher.cpp

Description: m_semantic m_vector没有根据配置变化的修复
Log: m_semantic m_vector没有根据配置变化的修复

fix: m_semantic m_vector没有根据配置变化的修复

---

src/dde-grand-search-daemon/searcher/semantic/database/anythingquery.cpp
src/dde-grand-search-daemon/searcher/semantic/database/featurequery.cpp
src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.cpp
src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.h
src/dde-grand-search-daemon/searcher/semantic/semantichelper.h
src/dde-grand-search-daemon/searcher/semantic/semanticsearcher.cpp
src/dde-grand-search-daemon/searcher/semantic/semanticsearcher_p.h
src/dde-grand-search-daemon/searcher/semantic/semanticworker.cpp
src/dde-grand-search-daemon/searcher/semantic/semanticworker.h
src/dde-grand-search-daemon/searcher/semantic/semanticworker_p.h
src/tools/semanticparser/semanticparser_p.h

Description: DSL检索性能优化：合并检索条件
Log:

feat: DSL检索性能优化：合并检索条件

---

src/dde-grand-search-daemon/searcher/semantic/database/anythingquery.cpp
src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.cpp
src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.h
src/dde-grand-search-daemon/searcher/semantic/semantichelper.h
src/dde-grand-search-daemon/searcher/semantic/semanticworker.cpp

Description: DSL性能优化：提供合并后的entity list
Log:

feat: DSL性能优化：提供合并后的entity list

---

src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.cpp

Description: DSL解析：时间合并bug的修复
Log:

fix: DSL解析：时间合并bug的修复

---

src/dde-grand-search-daemon/searcher/semantic/database/anythingquery.cpp
src/dde-grand-search-daemon/searcher/semantic/database/anythingquery.h
src/dde-grand-search-daemon/searcher/semantic/database/anythingquery_p.h
src/dde-grand-search-daemon/searcher/semantic/database/featurequery.cpp
src/dde-grand-search-daemon/searcher/semantic/database/featurequery.h
src/dde-grand-search-daemon/searcher/semantic/database/featurequery_p.h
src/dde-grand-search-daemon/searcher/semantic/database/fulltextquery.cpp
src/dde-grand-search-daemon/searcher/semantic/database/fulltextquery.h
src/dde-grand-search-daemon/searcher/semantic/database/fulltextquery_p.h
src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.cpp
src/dde-grand-search-daemon/searcher/semantic/semantichelper.cpp
src/dde-grand-search-daemon/searcher/semantic/semantichelper.h
src/dde-grand-search-daemon/searcher/semantic/semanticworker.cpp
src/dde-grand-search-daemon/searcher/semantic/semanticworker.h

Support multiple entity queries for DSL.
Log:
Task:

feat: query file by entities

---

src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.cpp
src/dde-grand-search-daemon/searcher/semantic/dslparser/dslparser.h
src/dde-grand-search-daemon/searcher/semantic/semanticworker.cpp

Description: DSL性能优化：Base层级合并逻辑的再完善
Log:

fix: DSL性能优化：Base层级合并逻辑的再完善

---

src/grand-search/CMakeLists.txt
src/grand-search/gui/searchconfig/blacklistwidget.cpp
src/grand-search/gui/searchconfig/indexwidget.cpp
src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.cpp
src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.h
src/grand-search/gui/searchconfig/searchenginewidget.cpp
src/grand-search/gui/searchconfig/tailerwidget.cpp
src/grand-search/gui/searchconfig/tipslabel.cpp
src/grand-search/gui/searchconfig/tipslabel.h

1. remove vector config
2. add auto index update 
Log:

feat: auto index

---

src/grand-search/CMakeLists.txt
src/grand-search/gui/searchconfig/llmwidget/downloader.cpp
src/grand-search/gui/searchconfig/llmwidget/downloader.h
src/grand-search/gui/searchconfig/llmwidget/llmwidget.cpp
src/grand-search/gui/searchconfig/llmwidget/llmwidget.h
src/grand-search/gui/searchconfig/llmwidget/modelmanagebutton.h

feat: 全局搜索改用http去下载模型

---

src/grand-search/gui/searchconfig/llmwidget/llmwidget.cpp

feat: 打断本地模型下载时添加条件判断

---

src/grand-search/gui/searchconfig/llmwidget/llmwidget.cpp
src/grand-search/gui/searchconfig/llmwidget/llmwidget.h

feat: 优化本地模型下载

---

src/grand-search/gui/exhibition/preview/generalwidget/aitoolbar.cpp

Description: 适配UOS AI进程未拉起的情况
Log:

feat: 适配UOS AI进程未拉起的情况

---

src/grand-search-dock-plugin/gui/grandsearchwidget.cpp

add dockplugin tooltip
Log: add dockplugin tooltip
Bug: https://pms.uniontech.com/bug-view-280351.html

fix: [tooltip] add dockplugin tooltip

---

translations/dde-grand-search_zh_CN.ts

feat: 增加模型卸载相关翻译

---

src/grand-search/gui/searchconfig/llmwidget/llmwidget.cpp
translations/dde-grand-search_zh_CN.ts

Description: 调整删除模型提示框样式，调整翻译
Log:
Bug:  https://pms.uniontech.com/bug-view-281889.html

fix: 调整删除模型提示框样式

---

src/grand-search/gui/searchconfig/intelligentretrieval/autoindexstatus.cpp
src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.cpp

Description: 自动更新索引的显示位置问题
Log:
Bug: https://pms.uniontech.com/bug-view-281811.html

fix: 自动更新索引的显示位置问题

---

debian/changelog

chore: updade changelog

---

src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.cpp

Description: AI搜索开关与自动更新索引开关不联动
Log:

feat: AI搜索开关与自动更新索引开关不联动

---

src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.cpp

Description: 关闭“AI智能搜索”时会同时关闭“自动更新索引”
Log:

feat: 关闭“AI智能搜索”时会同时关闭“自动更新索引”

---

src/grand-search/gui/entrance/entrancewidget.cpp
src/grand-search/gui/mainwindow.cpp

Adjust ui style.
Log:
Task: https://pms.uniontech.com/story-view-37579.html

feat: Adjust ui style

---

src/grand-search/gui/searchconfig/configwidget.cpp
src/grand-search/gui/searchconfig/indexwidget.cpp
src/grand-search/gui/searchconfig/indexwidget.h
src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.cpp
src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.h
src/grand-search/gui/searchconfig/llmwidget/downloader.cpp
src/grand-search/gui/searchconfig/llmwidget/downloader.h
src/grand-search/gui/searchconfig/llmwidget/llmwidget.cpp
src/grand-search/gui/searchconfig/llmwidget/llmwidget.h
translations/dde-grand-search_zh_CN.ts

Description: 1.模型下载进度显示2.下载中关闭窗口提示框
Log:

feat: 模型下载进度显示

---

src/dde-grand-search-daemon/searcher/semantic/semanticsearcher.cpp
src/dde-grand-search-daemon/searcher/semantic/semanticworker.cpp
src/grand-search/gui/exhibition/matchresult/groupwidget.cpp
src/grand-search/gui/exhibition/matchresult/groupwidget.h
src/grand-search/gui/searchconfig/configwidget.cpp
src/grand-search/gui/searchconfig/configwidget.h
src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.cpp
src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.h
src/grand-search/main.cpp
translations/dde-grand-search_zh_CN.ts

Description: AI搜索需求V1.4.1的开发
Log:

feat: AI搜索需求V1.4.1的开发

---

src/grand-search/gui/handlevisibility/handlevisibility.cpp
src/grand-search/gui/handlevisibility/handlevisibility.h
src/grand-search/gui/mainwindow.cpp
src/grand-search/utils/utils.cpp

Change the DBus interface name for V25.
Log: Adapt the DBus interface.

chore: Adapt the DBus

---

debian/changelog

New tag v5.5.10.
Log: v5.5.10 release.

chore: [tag]v5.5.10 release

---

src/configs/dbus/GrandSearchAdaptor.cpp
src/configs/dbus/GrandSearchAdaptor.h
src/configs/dbus/GrandSearchDaemonAdaptor.cpp
src/configs/dbus/GrandSearchDaemonAdaptor.h
src/configs/dbus/QueryLangAdaptor.cpp
src/configs/dbus/QueryLangAdaptor.h
src/configs/dbus/SearchPluginAdaptor.cpp
src/configs/dbus/SearchPluginAdaptor.h
src/configs/dbus/VectorIndexAdaptor.cpp
src/configs/dbus/VectorIndexAdaptor.h

Add dbus adaptor classes to handle communication between different components.
Log: add dbus adaptor classes for grand search

chore: add dbus adaptor classes for grand search

---

src/grand-search/gui/exhibition/matchresult/groupwidget.cpp
src/grand-search/gui/searchconfig/intelligentretrieval/intelligentretrievalwidget.cpp
src/grand-search/gui/searchconfig/llmwidget/llmwidget.cpp
src/tools/semanticparser/semanticparser.h
translations/dde-grand-search.ts
translations/dde-grand-search_zh_CN.ts

Using ULLM toreplace UOS AI Large Model.
Log:
Bug: bug#300257

fix: update text

---

CMakeLists.txt
debian/changelog
debian/rules
src/grand-search/CMakeLists.txt
src/grand-search/utils/utils.cpp
src/preview-plugin/CMakeLists.txt

The Dtk CMake module will use dtk release tool to get env version, but it may be incorrect that cause build blocked.
Log: Fix CI build issue.

fix: [CI]Fix CI build issue

---

src/grand-search/gui/exhibition/preview/generalwidget/aitoolbar.cpp
translations/dde-grand-search.ts
translations/dde-grand-search_zh_CN.ts

feat: Provide English prompt

---

debian/changelog

New version 6.0.0
Log: New version 6.0.0

chore: New version 6.0.0

---

src/grand-search/gui/exhibition/matchresult/groupwidget.cpp

Separate process parameters to stirng list.
Log:

fix: fail to start process

---

3rdparty/services/grandsearchsettingserviceadaptor.cpp
3rdparty/services/grandsearchsettingserviceadaptor.h
src/grand-search-dock-plugin/ddegrandsearchdockplugin.cpp
src/grand-search/CMakeLists.txt
src/grand-search/contacts/services/com.deepin.dde.GrandSearchSetting.service
src/grand-search/contacts/services/com.deepin.dde.GrandSearchSetting.xml
src/grand-search/contacts/services/grandsearchsettingservice.cpp
src/grand-search/contacts/services/grandsearchsettingservice.h
src/grand-search/contacts/services/grandsearchsettingservice_p.h
src/grand-search/setting_main.cpp

- Replace direct process call with dbus service call in dock plugin
- Add GrandSearchSetting dbus service and adaptor
- Create new setting service executable to handle settings dialog
Log: dock plugin cannot open settings dialog

fix: dock plugin cannot open settings dialog

---

debian/changelog

update version 6.0.2
Log: update version 6.0.2

chore: update version 6.0.2

---

debian/changelog

Bump version to 6.0.4
Log: Bump version to 6.0.4

chore: Bump version to 6.0.4

---

src/grand-search/gui/searchconfig/llmwidget/downloader.cpp
src/grand-search/gui/searchconfig/llmwidget/downloader.h
src/grand-search/gui/searchconfig/llmwidget/llmwidget.cpp

Description: uos model download link change
Log:

fix: uos model download link change

---

debian/changelog

Bump version to 6.0.5
Log: Bump version to 6.0.5

chore: Bump version to 6.0.5
